workflows:
  ios-ipa-sin-firma:
    name: iOS IPA Sin Firma
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ios --release --no-codesign
      - mkdir -p build/ios/ipa/Payload
      - cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
      - cd build/ios/ipa && zip -r Runner-unsigned.ipa Payload
    artifacts:
      - build/ios/ipa/Runner-unsigned.ipa
