DROP FUNCTION IF EXISTS public.normalizar_token_qr(TEXT);
DROP FUNCTION IF EXISTS public.buscar_qr_por_token(TEXT);
DROP FUNCTION IF EXISTS public.payload_qr_valido_tienda(TEXT, UUID);
DROP FUNCTION IF EXISTS public.generar_payload_qr_tienda(TEXT, BIGINT);
DROP FUNCTION IF EXISTS public.extraer_ubicacion_qr(JSONB, TEXT);
DROP FUNCTION IF EXISTS public.distancia_metros(DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia_qr(TEXT, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia_qr(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia_qr(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia_qr(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia_qr(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia_qr(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT, UUID, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(TEXT, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT, UUID, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(TEXT, VARCHAR);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(VARCHAR, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(TEXT, TIMESTAMPTZ, TEXT);
DROP FUNCTION IF EXISTS public.registrar_marcacion_asistencia(TEXT, TIMESTAMP WITH TIME ZONE, TEXT);
DROP FUNCTION IF EXISTS public.debug_qr_token(TEXT);
DROP FUNCTION IF EXISTS public.debug_marcacion_qr(TEXT, TEXT);
DROP FUNCTION IF EXISTS public.obtener_asistencia_hoy(TEXT, DATE);
DROP FUNCTION IF EXISTS public.obtener_historial_asistencias_mes(TEXT, INT, INT);
DROP FUNCTION IF EXISTS public.registrar_tracking_personal(TEXT, TEXT, TEXT, TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS public.registrar_tracking_personal(TEXT, TEXT, TEXT, TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS public.obtener_tracking_personal(TEXT, TIMESTAMPTZ, TIMESTAMPTZ);

ALTER TABLE public.asistencia
    ADD COLUMN IF NOT EXISTS ubicaciones JSONB NOT NULL DEFAULT '{}'::JSONB;

ALTER TABLE public.asistencia
    ADD COLUMN IF NOT EXISTS justificado BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS public.marcacion_offline_evento (
    evento_id UUID PRIMARY KEY,
    dni_trabajador TEXT NOT NULL,
    fecha DATE NOT NULL,
    tipo_marcacion TEXT NOT NULL CHECK (tipo_marcacion IN (
        'horario_entrada',
        'horario_inicio_receso',
        'horario_fin_receso',
        'horario_salida'
    )),
    marcado_en TIMESTAMPTZ NOT NULL,
    id_asistencia UUID NOT NULL,
    recibido_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_marcacion_offline_evento_dni_fecha
    ON public.marcacion_offline_evento (dni_trabajador, fecha);

ALTER TABLE public.marcacion_offline_evento ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.marcacion_offline_evento FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS public.asistencia_multiple (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_trabajador TEXT,
    id_tienda TEXT,
    hora_marca TIMESTAMPTZ,
    ubicacion JSONB NOT NULL DEFAULT '{}'::JSONB,
    tipo TEXT NOT NULL DEFAULT 'MULTIPLE',
    CONSTRAINT asistencia_multiple_pkey PRIMARY KEY (id)
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'id_asistencia_multiple'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'id'
    ) THEN
        ALTER TABLE public.asistencia_multiple
            RENAME COLUMN id_asistencia_multiple TO id;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'id'
    ) THEN
        ALTER TABLE public.asistencia_multiple
            ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_index i
        INNER JOIN pg_class c ON c.oid = i.indrelid
        INNER JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname = 'asistencia_multiple'
          AND i.indisprimary
    ) THEN
        ALTER TABLE public.asistencia_multiple
            ADD CONSTRAINT asistencia_multiple_pkey PRIMARY KEY (id);
    END IF;
END $$;

ALTER TABLE public.asistencia_multiple
    ADD COLUMN IF NOT EXISTS id_trabajador TEXT,
    ADD COLUMN IF NOT EXISTS id_tienda TEXT,
    ADD COLUMN IF NOT EXISTS hora_marca TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS ubicacion JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS tipo TEXT NOT NULL DEFAULT 'MULTIPLE';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'ubicacion'
          AND udt_name <> 'jsonb'
    ) THEN
        ALTER TABLE public.asistencia_multiple
            ALTER COLUMN ubicacion DROP DEFAULT;
        ALTER TABLE public.asistencia_multiple
            ALTER COLUMN ubicacion TYPE JSONB
            USING CASE
                WHEN ubicacion IS NULL OR trim(ubicacion::TEXT) = '' THEN '{}'::JSONB
                ELSE ubicacion::JSONB
            END;
    END IF;
END $$;

UPDATE public.asistencia_multiple
SET ubicacion = '{}'::JSONB
WHERE ubicacion IS NULL;

UPDATE public.asistencia_multiple
SET tipo = CASE
    WHEN upper(trim(COALESCE(tipo, ''))) = 'NORMAL' THEN 'NORMAL'
    ELSE 'MULTIPLE'
END;

ALTER TABLE public.asistencia_multiple
    ALTER COLUMN id_trabajador TYPE TEXT USING id_trabajador::TEXT,
    ALTER COLUMN id_tienda TYPE TEXT USING id_tienda::TEXT,
    ALTER COLUMN hora_marca TYPE TIMESTAMPTZ USING hora_marca::TIMESTAMPTZ,
    ALTER COLUMN ubicacion SET DEFAULT '{}'::JSONB,
    ALTER COLUMN ubicacion SET NOT NULL,
    ALTER COLUMN tipo TYPE TEXT USING tipo::TEXT,
    ALTER COLUMN tipo SET DEFAULT 'MULTIPLE',
    ALTER COLUMN tipo SET NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'ubicaciones'
    ) THEN
        UPDATE public.asistencia_multiple
        SET
            id_trabajador = COALESCE(
                NULLIF(ubicaciones ->> 'dni_trabajador', ''),
                NULLIF(id_trabajador, ''),
                NULLIF(ubicaciones ->> 'id_trabajador', '')
            ),
            id_tienda = COALESCE(
                NULLIF(ubicaciones ->> 'id_tienda_qr', ''),
                NULLIF(id_tienda, ''),
                NULLIF(ubicaciones ->> 'id_tienda_asignada', '')
            ),
            ubicacion = CASE
                WHEN ubicacion IS NULL OR ubicacion = '{}'::JSONB THEN jsonb_strip_nulls(jsonb_build_object(
                    'latitud', ubicaciones -> 'latitud',
                    'longitud', ubicaciones -> 'longitud'
                ))
                ELSE ubicacion
            END,
            tipo = CASE
                WHEN upper(COALESCE(ubicaciones ->> 'tipo', '')) = 'NORMAL'
                  OR lower(COALESCE(ubicaciones ->> 'origen', '')) = 'normal'
                THEN 'NORMAL'
                ELSE 'MULTIPLE'
            END
        WHERE ubicaciones IS NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'Fecha'
    ) THEN
        UPDATE public.asistencia_multiple
        SET hora_marca = COALESCE(hora_marca, "Fecha"::TIMESTAMPTZ)
        WHERE hora_marca IS NULL
          AND "Fecha" IS NOT NULL;
    END IF;
END $$;

UPDATE public.asistencia_multiple
SET
    tipo = CASE
        WHEN upper(trim(COALESCE(tipo, ''))) = 'NORMAL'
          OR lower(COALESCE(ubicacion ->> 'origen', '')) = 'normal'
        THEN 'NORMAL'
        ELSE 'MULTIPLE'
    END,
    ubicacion = jsonb_strip_nulls(jsonb_build_object(
        'latitud', ubicacion -> 'latitud',
        'longitud', ubicacion -> 'longitud'
    ));

UPDATE public.asistencia_multiple m
SET ubicacion = marca.ubicacion
FROM public.asistencia a
CROSS JOIN LATERAL (
    VALUES
        (a.horario_entrada, a.ubicaciones -> 'horario_entrada'),
        (a.horario_inicio_receso, a.ubicaciones -> 'horario_inicio_receso'),
        (a.horario_fin_receso, a.ubicaciones -> 'horario_fin_receso'),
        (a.horario_salida, a.ubicaciones -> 'horario_salida')
) AS marca(hora, ubicacion)
WHERE upper(COALESCE(m.tipo, '')) = 'NORMAL'
  AND m.id_trabajador::TEXT = a.dni_trabajador::TEXT
  AND m.hora_marca = marca.hora
  AND marca.ubicacion IS NOT NULL
  AND marca.ubicacion <> '{}'::JSONB
  AND (
      m.ubicacion IS NULL
      OR m.ubicacion = '{}'::JSONB
      OR (
          COALESCE(NULLIF(m.ubicacion ->> 'latitud', '')::DOUBLE PRECISION, 0) = 0
          AND COALESCE(NULLIF(m.ubicacion ->> 'longitud', '')::DOUBLE PRECISION, 0) = 0
      )
  );

ALTER TABLE public.asistencia_multiple
    DROP CONSTRAINT IF EXISTS asistencia_multiple_tipo_check;

ALTER TABLE public.asistencia_multiple
    ADD CONSTRAINT asistencia_multiple_tipo_check
    CHECK (tipo IN ('NORMAL', 'MULTIPLE'));

ALTER TABLE public.asistencia_multiple
    DROP COLUMN IF EXISTS id_asistencia_multiple,
    DROP COLUMN IF EXISTS id_trabajador_nombre,
    DROP COLUMN IF EXISTS id_trabajador_cargo,
    DROP COLUMN IF EXISTS id_tienda_nombre,
    DROP COLUMN IF EXISTS id_tienda_direccion,
    DROP COLUMN IF EXISTS ubicaciones,
    DROP COLUMN IF EXISTS "Fecha",
    DROP COLUMN IF EXISTS created_at;

ALTER TABLE public.asistencia
    DROP COLUMN IF EXISTS latitud_entrada,
    DROP COLUMN IF EXISTS longitud_entrada,
    DROP COLUMN IF EXISTS latitud_inicio_receso,
    DROP COLUMN IF EXISTS longitud_inicio_receso,
    DROP COLUMN IF EXISTS latitud_fin_receso,
    DROP COLUMN IF EXISTS longitud_fin_receso,
    DROP COLUMN IF EXISTS latitud_salida,
    DROP COLUMN IF EXISTS longitud_salida;

CREATE OR REPLACE FUNCTION public.normalizar_token_qr(
    p_raw TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_raw TEXT := trim(COALESCE(p_raw, ''));
    v_json JSONB;
    v_token TEXT;
BEGIN
    IF v_raw = '' THEN
        RETURN '';
    END IF;

    IF v_raw LIKE 'app-qr-dinamico://%' THEN
        RETURN v_raw;
    END IF;

    BEGIN
        v_json := v_raw::JSONB;

        IF jsonb_typeof(v_json) = 'array' AND jsonb_array_length(v_json) > 0 THEN
            v_json := v_json -> 0;
        END IF;

        IF jsonb_typeof(v_json) = 'object' THEN
            v_token := COALESCE(
                v_json ->> 'token',
                v_json ->> 'qr_token',
                v_json ->> 'codigo',
                v_json ->> 'code',
                v_json ->> 'value'
            );
            IF v_token IS NOT NULL AND trim(v_token) <> '' THEN
                v_raw := trim(v_token);
            END IF;
        ELSIF jsonb_typeof(v_json) = 'string' THEN
            v_raw := trim(v_json #>> '{}');
        END IF;
    EXCEPTION WHEN others THEN
        NULL;
    END;

    IF v_raw LIKE 'app-qr-dinamico://%' THEN
        RETURN v_raw;
    END IF;

    v_token := substring(v_raw from '(?:token|qr|code)=([^&?#[:space:]]+)');
    IF v_token IS NOT NULL AND trim(v_token) <> '' THEN
        v_raw := trim(v_token);
    END IF;

    v_token := substring(v_raw from '([0-9a-fA-F]{32,})');
    IF v_token IS NOT NULL AND trim(v_token) <> '' THEN
        v_raw := trim(v_token);
    END IF;

    RETURN trim(BOTH '"' FROM trim(v_raw));
END;
$$;

REVOKE ALL ON FUNCTION public.normalizar_token_qr(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.normalizar_token_qr(TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.normalizar_token_qr(TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.buscar_qr_por_token(
    p_token TEXT
)
RETURNS TABLE (
    id UUID,
    id_tienda UUID,
    token VARCHAR(512),
    fecha_creada TIMESTAMPTZ,
    ubicacion JSONB,
    nombre_tienda VARCHAR(150),
    direccion VARCHAR(255)
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_token TEXT := public.normalizar_token_qr(p_token);
BEGIN
    RETURN QUERY
    SELECT
        q.id,
        q.id_tienda,
        q.token,
        q.fecha_creada,
        COALESCE(q.ubicacion, '{}'::JSONB) AS ubicacion,
        COALESCE(t.nombre, 'Tienda') AS nombre_tienda,
        COALESCE(t.direccion, '') AS direccion
    FROM public.qr q
    INNER JOIN public.tienda t ON t.id_tienda = q.id_tienda
    WHERE t.estado = TRUE
      AND (
          trim(q.token::TEXT) = v_token
          OR public.payload_qr_valido_tienda(v_token, q.id_tienda)
      )
    LIMIT 1;
END;
$$;

REVOKE ALL ON FUNCTION public.buscar_qr_por_token(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.buscar_qr_por_token(TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.buscar_qr_por_token(TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.generar_payload_qr_tienda(
    p_token TEXT,
    p_slot BIGINT DEFAULT NULL
) RETURNS TEXT
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $$
DECLARE
    v_slot BIGINT := COALESCE(p_slot, floor(extract(epoch FROM NOW()) / 30)::BIGINT);
    v_firma TEXT;
BEGIN
    v_firma := md5(trim(p_token) || ':' || v_slot::TEXT || ':qr_dinamico:v2');
    RETURN 'app-qr-dinamico://' || v_slot::TEXT || '/' || v_firma;
END;
$$;

REVOKE ALL ON FUNCTION public.generar_payload_qr_tienda(TEXT, BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.generar_payload_qr_tienda(TEXT, BIGINT) TO anon;
GRANT EXECUTE ON FUNCTION public.generar_payload_qr_tienda(TEXT, BIGINT) TO authenticated;

CREATE OR REPLACE FUNCTION public.payload_qr_valido_tienda(
    p_payload TEXT,
    p_id_tienda UUID
) RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $$
DECLARE
    v_payload TEXT := trim(COALESCE(p_payload, ''));
    v_slot_actual BIGINT := floor(extract(epoch FROM NOW()) / 30)::BIGINT;
    v_slot BIGINT;
BEGIN
    FOR v_slot IN (v_slot_actual - 2)..(v_slot_actual + 2) LOOP
        IF EXISTS (
            SELECT 1
            FROM public.qr q
            INNER JOIN public.tienda t ON t.id_tienda = q.id_tienda
            WHERE q.id_tienda = p_id_tienda
              AND t.estado = TRUE
              AND v_payload = public.generar_payload_qr_tienda(q.token, v_slot)
        ) THEN
            RETURN TRUE;
        END IF;
    END LOOP;

    RETURN FALSE;
END;
$$;

REVOKE ALL ON FUNCTION public.payload_qr_valido_tienda(TEXT, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.payload_qr_valido_tienda(TEXT, UUID) TO anon;
GRANT EXECUTE ON FUNCTION public.payload_qr_valido_tienda(TEXT, UUID) TO authenticated;

CREATE OR REPLACE FUNCTION public.extraer_ubicacion_qr(
    p_ubicacion JSONB,
    p_tipo TEXT DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql
IMMUTABLE
SET search_path = public
AS $$
DECLARE
    v_ubicacion JSONB := COALESCE(p_ubicacion, '{}'::JSONB);
    v_tipo TEXT := lower(trim(COALESCE(p_tipo, '')));
    v_key TEXT;
    v_value JSONB;
BEGIN
    IF jsonb_typeof(v_ubicacion) IS DISTINCT FROM 'object' THEN
        RETURN NULL;
    END IF;

    IF (
        v_ubicacion ?| ARRAY['latitud', 'latitude', 'lat']
        AND v_ubicacion ?| ARRAY['longitud', 'longitude', 'lng', 'lon']
    ) THEN
        RETURN jsonb_build_object(
            'latitud', COALESCE(v_ubicacion -> 'latitud', v_ubicacion -> 'latitude', v_ubicacion -> 'lat'),
            'longitud', COALESCE(v_ubicacion -> 'longitud', v_ubicacion -> 'longitude', v_ubicacion -> 'lng', v_ubicacion -> 'lon')
        );
    END IF;

    v_tipo := regexp_replace(v_tipo, '[[:space:]]+', '_', 'g');
    FOR v_key IN
        SELECT unnest(ARRAY[
            NULLIF(v_tipo, ''),
            CASE
                WHEN v_tipo IN ('entrada', 'horario_entrada') THEN 'horario_entrada'
                WHEN v_tipo IN ('inicio_de_receso', 'inicio_receso', 'horario_inicio_receso') THEN 'horario_inicio_receso'
                WHEN v_tipo IN ('fin_de_receso', 'fin_receso', 'horario_fin_receso') THEN 'horario_fin_receso'
                WHEN v_tipo IN ('salida', 'horario_salida') THEN 'horario_salida'
                ELSE NULL
            END
        ])
    LOOP
        IF v_key IS NULL OR NOT (v_ubicacion ? v_key) THEN
            CONTINUE;
        END IF;

        v_value := v_ubicacion -> v_key;
        IF jsonb_typeof(v_value) = 'object'
           AND v_value ?| ARRAY['latitud', 'latitude', 'lat']
           AND v_value ?| ARRAY['longitud', 'longitude', 'lng', 'lon'] THEN
            RETURN jsonb_build_object(
                'latitud', COALESCE(v_value -> 'latitud', v_value -> 'latitude', v_value -> 'lat'),
                'longitud', COALESCE(v_value -> 'longitud', v_value -> 'longitude', v_value -> 'lng', v_value -> 'lon')
            );
        END IF;
    END LOOP;

    FOR v_key, v_value IN
        SELECT key, value FROM jsonb_each(v_ubicacion)
    LOOP
        IF jsonb_typeof(v_value) = 'object'
           AND v_value ?| ARRAY['latitud', 'latitude', 'lat']
           AND v_value ?| ARRAY['longitud', 'longitude', 'lng', 'lon'] THEN
            RETURN jsonb_build_object(
                'latitud', COALESCE(v_value -> 'latitud', v_value -> 'latitude', v_value -> 'lat'),
                'longitud', COALESCE(v_value -> 'longitud', v_value -> 'longitude', v_value -> 'lng', v_value -> 'lon')
            );
        END IF;
    END LOOP;

    RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.extraer_ubicacion_qr(JSONB, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.extraer_ubicacion_qr(JSONB, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.extraer_ubicacion_qr(JSONB, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.distancia_metros(
    p_latitud_a DOUBLE PRECISION,
    p_longitud_a DOUBLE PRECISION,
    p_latitud_b DOUBLE PRECISION,
    p_longitud_b DOUBLE PRECISION
) RETURNS DOUBLE PRECISION
LANGUAGE sql
IMMUTABLE
STRICT
SET search_path = public
AS $$
    SELECT 6371000.0 * 2.0 * asin(LEAST(1.0, sqrt(
        power(sin(radians((p_latitud_b - p_latitud_a) / 2.0)), 2) +
        cos(radians(p_latitud_a)) *
        cos(radians(p_latitud_b)) *
        power(sin(radians((p_longitud_b - p_longitud_a) / 2.0)), 2)
    )));
$$;

REVOKE ALL ON FUNCTION public.distancia_metros(DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.distancia_metros(DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION) TO anon;
GRANT EXECUTE ON FUNCTION public.distancia_metros(DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION) TO authenticated;

CREATE OR REPLACE FUNCTION public.registrar_marcacion_asistencia(
    p_dni TEXT,
    p_token TEXT,
    p_latitud DOUBLE PRECISION DEFAULT NULL,
    p_longitud DOUBLE PRECISION DEFAULT NULL,
    p_tipo_jornada_manual TEXT DEFAULT NULL,
    p_marcado_en TIMESTAMPTZ DEFAULT NULL,
    p_evento_id UUID DEFAULT NULL,
    p_tipo_marcacion_esperado TEXT DEFAULT NULL,
    p_dispositivo_id UUID DEFAULT NULL,
    p_dispositivo_secreto TEXT DEFAULT NULL
)
RETURNS TABLE (
    ok BOOLEAN,
    mensaje TEXT,
    tipo_marcacion TEXT,
    id_asistencia UUID,
    fecha_asistencia DATE,
    horario_entrada TIMESTAMPTZ,
    horario_inicio_receso TIMESTAMPTZ,
    horario_fin_receso TIMESTAMPTZ,
    horario_salida TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_ahora TIMESTAMPTZ := date_trunc(
        'second',
        COALESCE(p_marcado_en, now())
    );
    v_fecha DATE := (v_ahora AT TIME ZONE 'America/Lima')::DATE;
    v_token TEXT := public.normalizar_token_qr(p_token);
    v_asistencia public.asistencia%ROWTYPE;
    v_ultima TIMESTAMPTZ;
    v_restante INTERVAL;
    v_minutos INTEGER;
    v_tipo TEXT;
    v_trabajador_activo BOOLEAN := FALSE;
    v_biometria_requerida BOOLEAN := FALSE;
    v_dia_semana TEXT;
    v_tiene_receso BOOLEAN := TRUE;
    v_tiene_horario BOOLEAN := FALSE;
    v_justificado BOOLEAN := FALSE;
    v_id_tienda_qr TEXT;
    v_nombre_tienda_qr TEXT;
    v_direccion_tienda_qr TEXT;
    v_ubicacion_qr JSONB := '{}'::JSONB;
    v_referencia_qr JSONB;
    v_detalle_ubicacion JSONB;
    v_distancia_qr DOUBLE PRECISION;
    v_ultima_tienda_tracking TEXT;
    v_ultimo_tipo_tracking TEXT;
    v_tipo_jornada_manual TEXT;
BEGIN
    IF p_marcado_en IS NOT NULL AND p_evento_id IS NULL THEN
        RETURN QUERY SELECT FALSE, 'La fecha original requiere un identificador de evento offline.', NULL::TEXT,
            NULL::UUID, v_fecha AS fecha_asistencia, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    IF p_marcado_en IS NOT NULL
       AND (p_marcado_en > now() + INTERVAL '5 minutes'
            OR p_marcado_en < now() - INTERVAL '30 days') THEN
        RETURN QUERY SELECT FALSE, 'La fecha de la marcacion offline esta fuera del rango permitido.', NULL::TEXT,
            NULL::UUID, v_fecha AS fecha_asistencia, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    IF p_dni IS NULL OR trim(p_dni) = '' THEN
        RETURN QUERY SELECT FALSE, 'Falta el DNI del trabajador para registrar asistencia.', NULL::TEXT,
            NULL::UUID, v_fecha AS fecha_asistencia, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    SELECT t.estado, COALESCE(t.biometria_requerida, FALSE)
    INTO v_trabajador_activo, v_biometria_requerida
    FROM public.trabajador t
    WHERE t.dni = trim(p_dni)
    LIMIT 1;

    IF v_trabajador_activo IS DISTINCT FROM TRUE THEN
        RETURN QUERY SELECT FALSE, 'Trabajador no encontrado o inactivo.', NULL::TEXT,
            NULL::UUID, v_fecha AS fecha_asistencia, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    IF v_biometria_requerida
       AND NOT public.dispositivo_trabajador_valido(
           trim(p_dni),
           p_dispositivo_id,
           p_dispositivo_secreto
       ) THEN
        RETURN QUERY SELECT FALSE,
            'Este dispositivo no esta autorizado para registrar la asistencia del trabajador.',
            NULL::TEXT,
            NULL::UUID,
            v_fecha AS fecha_asistencia,
            NULL::TIMESTAMPTZ,
            NULL::TIMESTAMPTZ,
            NULL::TIMESTAMPTZ,
            NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    IF p_evento_id IS NOT NULL THEN
        PERFORM pg_advisory_xact_lock(hashtext(p_evento_id::TEXT));
        SELECT e.tipo_marcacion
        INTO v_tipo
        FROM public.marcacion_offline_evento e
        WHERE e.evento_id = p_evento_id
          AND e.dni_trabajador = trim(p_dni)
        LIMIT 1;

        IF v_tipo IS NOT NULL THEN
            SELECT a.*
            INTO v_asistencia
            FROM public.marcacion_offline_evento e
            JOIN public.asistencia a ON a.id_asistencia = e.id_asistencia
            WHERE e.evento_id = p_evento_id
              AND e.dni_trabajador = trim(p_dni)
            LIMIT 1;

            IF v_asistencia.id_asistencia IS NOT NULL THEN
                RETURN QUERY SELECT TRUE,
                    CASE v_tipo
                        WHEN 'horario_entrada' THEN 'Entrada'
                        WHEN 'horario_inicio_receso' THEN 'Inicio de receso'
                        WHEN 'horario_fin_receso' THEN 'Fin de receso'
                        WHEN 'horario_salida' THEN 'Salida'
                        ELSE v_tipo
                    END,
                    v_tipo,
                    v_asistencia.id_asistencia,
                    v_asistencia.fecha AS fecha_asistencia,
                    v_asistencia.horario_entrada,
                    v_asistencia.horario_inicio_receso,
                    v_asistencia.horario_fin_receso,
                    v_asistencia.horario_salida;
                RETURN;
            END IF;
        END IF;
    END IF;

    SELECT
        q.id_tienda::TEXT,
        COALESCE(q.ubicacion, '{}'::JSONB),
        COALESCE(ti.nombre, 'Tienda')::TEXT,
        COALESCE(ti.direccion, '')::TEXT
    INTO
        v_id_tienda_qr,
        v_ubicacion_qr,
        v_nombre_tienda_qr,
        v_direccion_tienda_qr
    FROM public.qr q
    INNER JOIN public.tienda ti ON ti.id_tienda = q.id_tienda
    WHERE ti.estado = TRUE
      AND (
          trim(q.token::TEXT) = v_token
          OR public.payload_qr_valido_tienda(v_token, q.id_tienda)
      )
    LIMIT 1;

    IF v_id_tienda_qr IS NULL OR v_id_tienda_qr = '' THEN
        RETURN QUERY SELECT FALSE, 'QR invalido, vencido o no pertenece a una tienda activa.', NULL::TEXT,
            NULL::UUID, v_fecha AS fecha_asistencia, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    SELECT
        a.id_tienda::TEXT,
        upper(COALESCE(a.tipo, 'MULTIPLE'))::TEXT
    INTO
        v_ultima_tienda_tracking,
        v_ultimo_tipo_tracking
    FROM public.asistencia_multiple a
    WHERE a.id_trabajador::TEXT = trim(p_dni)
      AND (a.hora_marca AT TIME ZONE 'America/Lima')::DATE = v_fecha
    ORDER BY a.hora_marca DESC, a.id DESC
    LIMIT 1;

    IF v_ultimo_tipo_tracking = 'MULTIPLE'
       AND COALESCE(v_ultima_tienda_tracking, '') <> COALESCE(v_id_tienda_qr, '') THEN
        RETURN QUERY SELECT FALSE, 'Tu ultima marca de tracking fue en otra sede. Registra tracking en esta sede antes de marcar asistencia.',
            NULL::TEXT,
            NULL::UUID,
            v_fecha AS fecha_asistencia,
            NULL::TIMESTAMPTZ,
            NULL::TIMESTAMPTZ,
            NULL::TIMESTAMPTZ,
            NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    v_dia_semana := CASE extract(isodow FROM v_fecha)::INT
        WHEN 1 THEN 'lunes'
        WHEN 2 THEN 'martes'
        WHEN 3 THEN 'miercoles'
        WHEN 4 THEN 'jueves'
        WHEN 5 THEN 'viernes'
        WHEN 6 THEN 'sabado'
        WHEN 7 THEN 'domingo'
    END;

    SELECT
        TRUE,
        NOT (
            h.horario_inicio_receso IS NULL
            AND h.horario_fin_receso IS NULL
        )
    INTO
        v_tiene_horario,
        v_tiene_receso
    FROM public.horario_trabajador h
    WHERE h.dni_trabajador = trim(p_dni)
      AND h.dia_semana::TEXT = v_dia_semana
    LIMIT 1;

    v_tiene_horario := COALESCE(v_tiene_horario, FALSE);
    v_tiene_receso := COALESCE(v_tiene_receso, TRUE);
    v_justificado := v_tiene_horario;
    v_tipo_jornada_manual := lower(trim(COALESCE(p_tipo_jornada_manual, '')));

    IF NOT v_tiene_horario THEN
        IF v_tipo_jornada_manual IN ('parttime', 'part_time', '2_marcas') THEN
            v_tiene_receso := FALSE;
            v_justificado := FALSE;
        ELSIF v_tipo_jornada_manual IN ('fulltime', 'full_time', '4_marcas') THEN
            v_tiene_receso := TRUE;
            v_justificado := FALSE;
        END IF;
    END IF;

    SELECT *
    INTO v_asistencia
    FROM public.asistencia a
    WHERE a.dni_trabajador = trim(p_dni)
      AND a.fecha = v_fecha
    LIMIT 1;

    IF v_asistencia.id_asistencia IS NULL THEN
        INSERT INTO public.asistencia (
            dni_trabajador,
            fecha,
            horario_entrada,
            horario_inicio_receso,
            horario_fin_receso,
            horario_salida,
            ubicaciones,
            justificado
        )
        VALUES (
            trim(p_dni),
            v_fecha,
            NULL,
            NULL,
            NULL,
            NULL,
            CASE
                WHEN v_tipo_jornada_manual <> '' THEN jsonb_build_object(
                    '_jornada_manual',
                    jsonb_build_object(
                        'tipo_jornada', v_tipo_jornada_manual,
                        'tiene_receso', v_tiene_receso,
                        'registrado_en', v_ahora
                    )
                )
                ELSE '{}'::JSONB
            END,
            v_justificado
        )
        RETURNING *
        INTO v_asistencia;
    END IF;

    IF NOT v_tiene_horario THEN
        v_tipo_jornada_manual := lower(trim(COALESCE(
            NULLIF(v_tipo_jornada_manual, ''),
            v_asistencia.ubicaciones #>> '{_jornada_manual,tipo_jornada}',
            v_asistencia.ubicaciones ->> 'tipo_jornada_manual',
            ''
        )));

        IF v_tipo_jornada_manual IN ('parttime', 'part_time', '2_marcas') THEN
            v_tiene_receso := FALSE;
            v_justificado := FALSE;
        ELSIF v_tipo_jornada_manual IN ('fulltime', 'full_time', '4_marcas') THEN
            v_tiene_receso := TRUE;
            v_justificado := FALSE;
        END IF;

        IF v_tipo_jornada_manual <> '' THEN
            UPDATE public.asistencia
            SET
                justificado = v_justificado,
                ubicaciones = jsonb_set(
                    COALESCE(ubicaciones, '{}'::JSONB),
                    '{_jornada_manual}',
                    jsonb_build_object(
                        'tipo_jornada', v_tipo_jornada_manual,
                        'tiene_receso', v_tiene_receso,
                        'registrado_en', v_ahora
                    ),
                    TRUE
                )
            WHERE asistencia.id_asistencia = v_asistencia.id_asistencia
            RETURNING *
            INTO v_asistencia;
        END IF;
    END IF;

    SELECT MAX(marca)
    INTO v_ultima
    FROM (
        VALUES
            (v_asistencia.horario_entrada),
            (v_asistencia.horario_inicio_receso),
            (v_asistencia.horario_fin_receso),
            (v_asistencia.horario_salida)
    ) AS marcas(marca);

    IF v_ultima IS NOT NULL THEN
        v_restante := INTERVAL '10 minutes' - (v_ahora - v_ultima);
        IF v_restante > INTERVAL '0 seconds' THEN
            v_minutos := CEIL(EXTRACT(EPOCH FROM v_restante) / 60.0)::INTEGER;
            RETURN QUERY SELECT FALSE, 'Debes esperar ' || v_minutos || ' minutos antes de volver a marcar',
                NULL::TEXT,
                v_asistencia.id_asistencia,
                v_asistencia.fecha AS fecha_asistencia,
                v_asistencia.horario_entrada,
                v_asistencia.horario_inicio_receso,
                v_asistencia.horario_fin_receso,
                v_asistencia.horario_salida;
            RETURN;
        END IF;
    END IF;

    IF v_asistencia.horario_entrada IS NULL THEN
        v_tipo := 'horario_entrada';
    ELSIF v_tiene_receso AND v_asistencia.horario_inicio_receso IS NULL THEN
        v_tipo := 'horario_inicio_receso';
    ELSIF v_tiene_receso AND v_asistencia.horario_fin_receso IS NULL THEN
        v_tipo := 'horario_fin_receso';
    ELSIF v_asistencia.horario_salida IS NULL THEN
        v_tipo := 'horario_salida';
    ELSE
        RETURN QUERY SELECT FALSE, 'Ya completaste todas las marcaciones de hoy',
            NULL::TEXT,
            v_asistencia.id_asistencia,
            v_asistencia.fecha AS fecha_asistencia,
            v_asistencia.horario_entrada,
            v_asistencia.horario_inicio_receso,
            v_asistencia.horario_fin_receso,
            v_asistencia.horario_salida;
        RETURN;
    END IF;

    IF p_evento_id IS NOT NULL
       AND NULLIF(trim(COALESCE(p_tipo_marcacion_esperado, '')), '') IS NOT NULL
       AND v_tipo <> trim(p_tipo_marcacion_esperado) THEN
        RETURN QUERY SELECT FALSE,
            'El orden de la marca offline no coincide con la asistencia del servidor.',
            v_tipo,
            v_asistencia.id_asistencia,
            v_asistencia.fecha AS fecha_asistencia,
            v_asistencia.horario_entrada,
            v_asistencia.horario_inicio_receso,
            v_asistencia.horario_fin_receso,
            v_asistencia.horario_salida;
        RETURN;
    END IF;

    v_referencia_qr := public.extraer_ubicacion_qr(v_ubicacion_qr, v_tipo);
    IF v_referencia_qr IS NULL THEN
        RETURN QUERY SELECT FALSE, 'El QR no tiene ubicacion de referencia para validar el rango.',
            NULL::TEXT,
            v_asistencia.id_asistencia,
            v_asistencia.fecha AS fecha_asistencia,
            v_asistencia.horario_entrada,
            v_asistencia.horario_inicio_receso,
            v_asistencia.horario_fin_receso,
            v_asistencia.horario_salida;
        RETURN;
    END IF;

    IF NULLIF(v_referencia_qr ->> 'latitud', '') IS NULL
       OR NULLIF(v_referencia_qr ->> 'longitud', '') IS NULL THEN
        RETURN QUERY SELECT FALSE, 'El QR no tiene ubicacion de referencia para validar el rango.',
            NULL::TEXT,
            v_asistencia.id_asistencia,
            v_asistencia.fecha AS fecha_asistencia,
            v_asistencia.horario_entrada,
            v_asistencia.horario_inicio_receso,
            v_asistencia.horario_fin_receso,
            v_asistencia.horario_salida;
        RETURN;
    END IF;

    IF p_latitud IS NULL
       OR p_longitud IS NULL
       OR (
           abs(COALESCE(p_latitud, 0)) <= 0.000001
           AND abs(COALESCE(p_longitud, 0)) <= 0.000001
       ) THEN
        RETURN QUERY SELECT FALSE, 'No se pudo obtener tu ubicacion actual para validar el QR.',
            NULL::TEXT,
            v_asistencia.id_asistencia,
            v_asistencia.fecha AS fecha_asistencia,
            v_asistencia.horario_entrada,
            v_asistencia.horario_inicio_receso,
            v_asistencia.horario_fin_receso,
            v_asistencia.horario_salida;
        RETURN;
    END IF;

    v_distancia_qr := public.distancia_metros(
        NULLIF(v_referencia_qr ->> 'latitud', '')::DOUBLE PRECISION,
        NULLIF(v_referencia_qr ->> 'longitud', '')::DOUBLE PRECISION,
        p_latitud,
        p_longitud
    );

    IF v_distancia_qr > 150 THEN
        RETURN QUERY SELECT FALSE, 'Fuera del rango permitido del QR. Acercate a la sede para marcar.',
            NULL::TEXT,
            v_asistencia.id_asistencia,
            v_asistencia.fecha AS fecha_asistencia,
            v_asistencia.horario_entrada,
            v_asistencia.horario_inicio_receso,
            v_asistencia.horario_fin_receso,
            v_asistencia.horario_salida;
        RETURN;
    END IF;

    v_detalle_ubicacion := jsonb_strip_nulls(jsonb_build_object(
        'latitud', p_latitud,
        'longitud', p_longitud,
        'id_tienda_qr', v_id_tienda_qr,
        'nombre_tienda', v_nombre_tienda_qr,
        'direccion_tienda', v_direccion_tienda_qr
    ));

    IF v_tipo = 'horario_entrada' THEN
        UPDATE public.asistencia
        SET
            horario_entrada = v_ahora,
            justificado = v_justificado,
            ubicaciones = jsonb_set(
                COALESCE(ubicaciones, '{}'::JSONB),
                '{horario_entrada}',
                v_detalle_ubicacion,
                TRUE
            )
        WHERE asistencia.id_asistencia = v_asistencia.id_asistencia;
    ELSIF v_tipo = 'horario_inicio_receso' THEN
        UPDATE public.asistencia
        SET
            horario_inicio_receso = v_ahora,
            justificado = v_justificado,
            ubicaciones = jsonb_set(
                COALESCE(ubicaciones, '{}'::JSONB),
                '{horario_inicio_receso}',
                v_detalle_ubicacion,
                TRUE
            )
        WHERE asistencia.id_asistencia = v_asistencia.id_asistencia;
    ELSIF v_tipo = 'horario_fin_receso' THEN
        UPDATE public.asistencia
        SET
            horario_fin_receso = v_ahora,
            justificado = v_justificado,
            ubicaciones = jsonb_set(
                COALESCE(ubicaciones, '{}'::JSONB),
                '{horario_fin_receso}',
                v_detalle_ubicacion,
                TRUE
            )
        WHERE asistencia.id_asistencia = v_asistencia.id_asistencia;
    ELSIF v_tipo = 'horario_salida' THEN
        UPDATE public.asistencia
        SET
            horario_salida = v_ahora,
            justificado = v_justificado,
            ubicaciones = jsonb_set(
                COALESCE(ubicaciones, '{}'::JSONB),
                '{horario_salida}',
                v_detalle_ubicacion,
                TRUE
            )
        WHERE asistencia.id_asistencia = v_asistencia.id_asistencia;
    END IF;

    SELECT *
    INTO v_asistencia
    FROM public.asistencia a
    WHERE a.id_asistencia = v_asistencia.id_asistencia;

    IF p_evento_id IS NOT NULL THEN
        INSERT INTO public.marcacion_offline_evento (
            evento_id,
            dni_trabajador,
            fecha,
            tipo_marcacion,
            marcado_en,
            id_asistencia
        ) VALUES (
            p_evento_id,
            trim(p_dni),
            v_fecha,
            v_tipo,
            v_ahora,
            v_asistencia.id_asistencia
        )
        ON CONFLICT (evento_id) DO NOTHING;
    END IF;

    RETURN QUERY SELECT TRUE,
        CASE v_tipo
            WHEN 'horario_entrada' THEN 'Entrada'
            WHEN 'horario_inicio_receso' THEN 'Inicio de receso'
            WHEN 'horario_fin_receso' THEN 'Fin de receso'
            WHEN 'horario_salida' THEN 'Salida'
            ELSE v_tipo
        END,
        v_tipo,
        v_asistencia.id_asistencia,
        v_asistencia.fecha AS fecha_asistencia,
        v_asistencia.horario_entrada,
        v_asistencia.horario_inicio_receso,
        v_asistencia.horario_fin_receso,
        v_asistencia.horario_salida;
END;
$$;

REVOKE ALL ON FUNCTION public.registrar_marcacion_asistencia(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT, UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_marcacion_asistencia(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT, UUID, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_marcacion_asistencia(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT, UUID, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.registrar_marcacion_asistencia_qr(
    p_dni TEXT,
    p_token TEXT,
    p_latitud DOUBLE PRECISION DEFAULT NULL,
    p_longitud DOUBLE PRECISION DEFAULT NULL,
    p_tipo_jornada_manual TEXT DEFAULT NULL,
    p_marcado_en TIMESTAMPTZ DEFAULT NULL,
    p_evento_id UUID DEFAULT NULL,
    p_tipo_marcacion_esperado TEXT DEFAULT NULL,
    p_dispositivo_id UUID DEFAULT NULL,
    p_dispositivo_secreto TEXT DEFAULT NULL
)
RETURNS TABLE (
    ok BOOLEAN,
    mensaje TEXT,
    tipo_marcacion TEXT,
    id_asistencia UUID,
    fecha_asistencia DATE,
    horario_entrada TIMESTAMPTZ,
    horario_inicio_receso TIMESTAMPTZ,
    horario_fin_receso TIMESTAMPTZ,
    horario_salida TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT *
    FROM public.registrar_marcacion_asistencia(
        p_dni,
        p_token,
        p_latitud,
        p_longitud,
        p_tipo_jornada_manual,
        p_marcado_en,
        p_evento_id,
        p_tipo_marcacion_esperado,
        p_dispositivo_id,
        p_dispositivo_secreto
    );
$$;

REVOKE ALL ON FUNCTION public.registrar_marcacion_asistencia_qr(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT, UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_marcacion_asistencia_qr(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT, UUID, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_marcacion_asistencia_qr(TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TIMESTAMPTZ, UUID, TEXT, UUID, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.registrar_tracking_personal(
    p_dni TEXT,
    p_token TEXT DEFAULT NULL,
    p_id_tienda_qr TEXT DEFAULT NULL,
    p_nombre_tienda TEXT DEFAULT NULL,
    p_direccion_tienda TEXT DEFAULT NULL,
    p_latitud DOUBLE PRECISION DEFAULT NULL,
    p_longitud DOUBLE PRECISION DEFAULT NULL,
    p_nombre_trabajador TEXT DEFAULT NULL,
    p_cargo_trabajador TEXT DEFAULT NULL,
    p_id_trabajador TEXT DEFAULT NULL,
    p_id_tienda_asignada TEXT DEFAULT NULL,
    p_tipo_marcacion TEXT DEFAULT 'Marca',
    p_origen TEXT DEFAULT 'multiple',
    p_tipo TEXT DEFAULT NULL,
    p_registrado_en TEXT DEFAULT NULL
)
RETURNS TABLE (
    ok BOOLEAN,
    mensaje TEXT,
    fecha TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_token TEXT := public.normalizar_token_qr(COALESCE(p_token, ''));
    v_registrado_en TIMESTAMPTZ;
    v_id_tienda_qr TEXT;
    v_tipo TEXT;
    v_ubicacion JSONB;
    v_ubicacion_qr JSONB := '{}'::JSONB;
    v_referencia_qr JSONB;
    v_distancia_qr DOUBLE PRECISION;
BEGIN
    IF p_dni IS NULL OR trim(p_dni) = '' THEN
        RETURN QUERY SELECT FALSE, 'Falta el DNI del trabajador para registrar tracking.', NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    BEGIN
        v_registrado_en := COALESCE(NULLIF(trim(COALESCE(p_registrado_en, '')), '')::TIMESTAMPTZ, date_trunc('second', now()));
    EXCEPTION WHEN OTHERS THEN
        v_registrado_en := date_trunc('second', now());
    END;

    SELECT
        q.id_tienda::TEXT,
        COALESCE(q.ubicacion, '{}'::JSONB)
    INTO
        v_id_tienda_qr,
        v_ubicacion_qr
    FROM public.qr q
    INNER JOIN public.tienda t ON t.id_tienda = q.id_tienda
    WHERE t.estado = TRUE
      AND (
          trim(q.token::TEXT) = v_token
          OR public.payload_qr_valido_tienda(v_token, q.id_tienda)
      )
    LIMIT 1;

    v_id_tienda_qr := COALESCE(NULLIF(trim(COALESCE(p_id_tienda_qr, '')), ''), v_id_tienda_qr, '');
    v_tipo := CASE
        WHEN upper(trim(COALESCE(p_tipo, ''))) = 'NORMAL'
          OR lower(trim(COALESCE(p_origen, ''))) = 'normal'
        THEN 'NORMAL'
        ELSE 'MULTIPLE'
    END;
    v_ubicacion := jsonb_strip_nulls(jsonb_build_object(
        'latitud', p_latitud,
        'longitud', p_longitud
    ));

    IF v_tipo = 'MULTIPLE' AND NOT EXISTS (
        SELECT 1
        FROM public.asistencia a
        WHERE a.dni_trabajador::TEXT = trim(p_dni)
          AND a.fecha = (v_registrado_en AT TIME ZONE 'America/Lima')::DATE
          AND a.horario_entrada IS NOT NULL
          AND a.horario_entrada <= v_registrado_en
    ) THEN
        RETURN QUERY SELECT FALSE, 'Primero registra tu Entrada antes de usar Tracking.', NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    v_referencia_qr := public.extraer_ubicacion_qr(v_ubicacion_qr, p_tipo_marcacion);
    IF v_referencia_qr IS NULL THEN
        RETURN QUERY SELECT FALSE, 'El QR no tiene ubicacion de referencia para validar el rango.', NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    IF NULLIF(v_referencia_qr ->> 'latitud', '') IS NULL
       OR NULLIF(v_referencia_qr ->> 'longitud', '') IS NULL THEN
        RETURN QUERY SELECT FALSE, 'El QR no tiene ubicacion de referencia para validar el rango.', NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    IF p_latitud IS NULL
       OR p_longitud IS NULL
       OR (
           abs(COALESCE(p_latitud, 0)) <= 0.000001
           AND abs(COALESCE(p_longitud, 0)) <= 0.000001
       ) THEN
        RETURN QUERY SELECT FALSE, 'No se pudo obtener tu ubicacion actual para validar el QR.', NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    v_distancia_qr := public.distancia_metros(
        NULLIF(v_referencia_qr ->> 'latitud', '')::DOUBLE PRECISION,
        NULLIF(v_referencia_qr ->> 'longitud', '')::DOUBLE PRECISION,
        p_latitud,
        p_longitud
    );

    IF v_distancia_qr > 150 THEN
        RETURN QUERY SELECT FALSE, 'Fuera del rango permitido del QR. Acercate a la sede para marcar.', NULL::TIMESTAMPTZ;
        RETURN;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.asistencia_multiple a
        WHERE a.id_trabajador::TEXT = trim(p_dni)
          AND a.hora_marca = v_registrado_en
          AND COALESCE(a.id_tienda, '') = COALESCE(v_id_tienda_qr, '')
          AND COALESCE(a.tipo, '') = v_tipo
        LIMIT 1
    ) THEN
        UPDATE public.asistencia_multiple a
        SET ubicacion = v_ubicacion
        WHERE a.id_trabajador::TEXT = trim(p_dni)
          AND a.hora_marca = v_registrado_en
          AND COALESCE(a.id_tienda, '') = COALESCE(v_id_tienda_qr, '')
          AND COALESCE(a.tipo, '') = v_tipo
          AND v_ubicacion <> '{}'::JSONB
          AND (
              a.ubicacion IS NULL
              OR a.ubicacion = '{}'::JSONB
              OR (
                  COALESCE(NULLIF(a.ubicacion ->> 'latitud', '')::DOUBLE PRECISION, 0) = 0
                  AND COALESCE(NULLIF(a.ubicacion ->> 'longitud', '')::DOUBLE PRECISION, 0) = 0
              )
          );
        RETURN QUERY SELECT TRUE, 'Movimiento ya registrado', v_registrado_en;
        RETURN;
    END IF;

    INSERT INTO public.asistencia_multiple (
        id_trabajador,
        id_tienda,
        hora_marca,
        ubicacion,
        tipo
    )
    VALUES (
        trim(p_dni),
        v_id_tienda_qr,
        v_registrado_en,
        v_ubicacion,
        v_tipo
    );

    RETURN QUERY SELECT TRUE, 'Movimiento registrado', v_registrado_en;
END;
$$;

REVOKE ALL ON FUNCTION public.registrar_tracking_personal(TEXT, TEXT, TEXT, TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_tracking_personal(TEXT, TEXT, TEXT, TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_tracking_personal(TEXT, TEXT, TEXT, TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.obtener_tracking_personal(
    p_dni TEXT,
    p_inicio TIMESTAMPTZ,
    p_fin TIMESTAMPTZ
)
RETURNS TABLE (
    id BIGINT,
    id_trabajador TEXT,
    id_tienda TEXT,
    hora_marca TIMESTAMPTZ,
    ubicacion JSONB,
    tipo TEXT,
    nombre_tienda TEXT,
    direccion_tienda TEXT,
    nombre_trabajador TEXT,
    cargo_trabajador TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    SELECT
        a.id::BIGINT,
        a.id_trabajador::TEXT,
        a.id_tienda::TEXT,
        a.hora_marca::TIMESTAMPTZ,
        COALESCE(a.ubicacion, '{}'::JSONB),
        COALESCE(a.tipo, '')::TEXT,
        COALESCE(ti.nombre, 'Tienda')::TEXT,
        COALESCE(ti.direccion, '')::TEXT,
        COALESCE(tr.nombre, '')::TEXT,
        COALESCE(tr.cargo, '')::TEXT
    FROM public.asistencia_multiple a
    LEFT JOIN public.trabajador tr ON tr.dni::TEXT = a.id_trabajador::TEXT
    LEFT JOIN public.tienda ti ON ti.id_tienda::TEXT = a.id_tienda::TEXT
    WHERE a.id_trabajador = trim(p_dni)
      AND a.hora_marca >= p_inicio
      AND a.hora_marca < p_fin
    ORDER BY a.hora_marca ASC;
END;
$$;

REVOKE ALL ON FUNCTION public.obtener_tracking_personal(TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.obtener_tracking_personal(TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO anon;
GRANT EXECUTE ON FUNCTION public.obtener_tracking_personal(TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO authenticated;

CREATE OR REPLACE FUNCTION public.debug_qr_token(
    p_token TEXT
)
RETURNS TABLE (
    token_recibido TEXT,
    token_normalizado TEXT,
    encontrado BOOLEAN,
    total_qr BIGINT,
    token_encontrado TEXT,
    id_tienda UUID,
    usado BOOLEAN,
    session_id TEXT,
    usado_expira_en TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_token TEXT := public.normalizar_token_qr(p_token);
BEGIN
    RETURN QUERY
    SELECT
        p_token,
        v_token,
        q.id IS NOT NULL OR EXISTS (
            SELECT 1
            FROM public.qr q2
            INNER JOIN public.tienda ti2 ON ti2.id_tienda = q2.id_tienda
            WHERE ti2.estado = TRUE
              AND public.payload_qr_valido_tienda(v_token, q2.id_tienda)
        ),
        (SELECT COUNT(*) FROM public.qr),
        q.token::TEXT,
        q.id_tienda,
        CASE WHEN to_jsonb(q) ? 'usado' THEN (to_jsonb(q) ->> 'usado')::BOOLEAN ELSE NULL END,
        CASE WHEN to_jsonb(q) ? 'session_id' THEN to_jsonb(q) ->> 'session_id' ELSE NULL END,
        CASE
            WHEN to_jsonb(q) ? 'usado_expira_en'
            THEN (to_jsonb(q) ->> 'usado_expira_en')::TIMESTAMPTZ
            ELSE NULL
        END
    FROM (SELECT 1) s
    LEFT JOIN public.qr q ON trim(q.token::TEXT) = v_token
    LIMIT 1;
END;
$$;

REVOKE ALL ON FUNCTION public.debug_qr_token(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.debug_qr_token(TEXT) FROM anon;
REVOKE ALL ON FUNCTION public.debug_qr_token(TEXT) FROM authenticated;

CREATE OR REPLACE FUNCTION public.debug_marcacion_qr(
    p_dni TEXT,
    p_token TEXT
)
RETURNS TABLE (
    dni_normalizado TEXT,
    token_normalizado TEXT,
    id_tienda_qr UUID,
    trabajador_activo BOOLEAN,
    qr_plano_valido BOOLEAN,
    qr_dinamico_valido BOOLEAN,
    slot_supabase BIGINT,
    mensaje TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_dni TEXT := trim(COALESCE(p_dni, ''));
    v_token TEXT := public.normalizar_token_qr(p_token);
    v_id_tienda_qr UUID;
    v_activo BOOLEAN := FALSE;
    v_qr_plano BOOLEAN := FALSE;
    v_qr_dinamico BOOLEAN := FALSE;
BEGIN
    SELECT t.estado
    INTO v_activo
    FROM public.trabajador t
    WHERE t.dni = v_dni
    LIMIT 1;

    SELECT EXISTS (
        SELECT 1
        FROM public.qr q
        INNER JOIN public.tienda ti ON ti.id_tienda = q.id_tienda
        WHERE ti.estado = TRUE
          AND trim(q.token::TEXT) = v_token
    )
    INTO v_qr_plano;

    SELECT EXISTS (
        SELECT 1
        FROM public.qr q
        INNER JOIN public.tienda ti ON ti.id_tienda = q.id_tienda
        WHERE ti.estado = TRUE
          AND public.payload_qr_valido_tienda(v_token, q.id_tienda)
    )
    INTO v_qr_dinamico;

    SELECT q.id_tienda
    INTO v_id_tienda_qr
    FROM public.qr q
    INNER JOIN public.tienda ti ON ti.id_tienda = q.id_tienda
    WHERE ti.estado = TRUE
      AND (
          trim(q.token::TEXT) = v_token
          OR public.payload_qr_valido_tienda(v_token, q.id_tienda)
      )
    ORDER BY q.fecha_creada DESC
    LIMIT 1;

    RETURN QUERY
    SELECT
        v_dni,
        v_token,
        v_id_tienda_qr,
        COALESCE(v_activo, FALSE),
        v_qr_plano,
        v_qr_dinamico,
        floor(extract(epoch FROM NOW()) / 30)::BIGINT,
        CASE
            WHEN v_dni = '' THEN 'DNI vacio.'
            WHEN NOT EXISTS (SELECT 1 FROM public.trabajador t WHERE t.dni = v_dni) THEN 'Trabajador no encontrado.'
            WHEN COALESCE(v_activo, FALSE) = FALSE THEN 'Trabajador inactivo.'
            WHEN v_qr_plano OR v_qr_dinamico THEN 'QR valido para marcar.'
            ELSE 'QR vencido, token cacheado, tienda inactiva o reloj desfasado.'
        END;
END;
$$;

REVOKE ALL ON FUNCTION public.debug_marcacion_qr(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.debug_marcacion_qr(TEXT, TEXT) FROM anon;
REVOKE ALL ON FUNCTION public.debug_marcacion_qr(TEXT, TEXT) FROM authenticated;

CREATE OR REPLACE FUNCTION public.obtener_asistencia_hoy(
    p_dni TEXT,
    p_fecha DATE DEFAULT NULL
)
RETURNS TABLE (
    id_asistencia UUID,
    dni_trabajador VARCHAR,
    fecha DATE,
    horario_entrada TIMESTAMPTZ,
    horario_inicio_receso TIMESTAMPTZ,
    horario_fin_receso TIMESTAMPTZ,
    horario_salida TIMESTAMPTZ,
    ubicaciones JSONB,
    justificado BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_fecha DATE := COALESCE(p_fecha, (now() AT TIME ZONE 'America/Lima')::DATE);
BEGIN
    RETURN QUERY
    SELECT
        a.id_asistencia,
        a.dni_trabajador,
        a.fecha,
        a.horario_entrada,
        a.horario_inicio_receso,
        a.horario_fin_receso,
        a.horario_salida,
        COALESCE(a.ubicaciones, '{}'::JSONB),
        COALESCE(a.justificado, FALSE)
    FROM public.asistencia a
    WHERE a.dni_trabajador = trim(p_dni)
      AND a.fecha = v_fecha
    LIMIT 1;
END;
$$;

REVOKE ALL ON FUNCTION public.obtener_asistencia_hoy(TEXT, DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.obtener_asistencia_hoy(TEXT, DATE) TO anon;
GRANT EXECUTE ON FUNCTION public.obtener_asistencia_hoy(TEXT, DATE) TO authenticated;

CREATE OR REPLACE FUNCTION public.obtener_historial_asistencias_mes(
    p_dni TEXT,
    p_year INT,
    p_month INT
)
RETURNS TABLE (
    id_asistencia UUID,
    dni_trabajador VARCHAR,
    fecha DATE,
    horario_entrada TIMESTAMPTZ,
    horario_inicio_receso TIMESTAMPTZ,
    horario_fin_receso TIMESTAMPTZ,
    horario_salida TIMESTAMPTZ,
    ubicaciones JSONB,
    justificado BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_inicio_mes DATE;
    v_fin_mes DATE;
BEGIN
    v_inicio_mes := make_date(p_year, p_month, 1);
    v_fin_mes := (v_inicio_mes + INTERVAL '1 month' - INTERVAL '1 day')::DATE;

    RETURN QUERY
    SELECT
        a.id_asistencia,
        a.dni_trabajador,
        a.fecha,
        a.horario_entrada,
        a.horario_inicio_receso,
        a.horario_fin_receso,
        a.horario_salida,
        COALESCE(a.ubicaciones, '{}'::JSONB),
        COALESCE(a.justificado, FALSE)
    FROM public.asistencia a
    WHERE a.dni_trabajador = trim(p_dni)
      AND a.fecha >= v_inicio_mes
      AND a.fecha <= v_fin_mes
    ORDER BY a.fecha DESC;
END;
$$;

REVOKE ALL ON FUNCTION public.obtener_historial_asistencias_mes(TEXT, INT, INT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.obtener_historial_asistencias_mes(TEXT, INT, INT) TO anon;
GRANT EXECUTE ON FUNCTION public.obtener_historial_asistencias_mes(TEXT, INT, INT) TO authenticated;

NOTIFY pgrst, 'reload schema';

NOTIFY pgrst, 'reload schema';
