CREATE TABLE IF NOT EXISTS public.asistencia_multiple (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_trabajador TEXT,
    id_tienda TEXT,
    hora_marca TIMESTAMPTZ,
    ubicacion JSONB NOT NULL DEFAULT '{}'::JSONB,
    tipo TEXT NOT NULL DEFAULT 'MULTIPLE',
    CONSTRAINT asistencia_multiple_pkey PRIMARY KEY (id)
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'id_asistencia_multiple'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'id'
    ) THEN
        ALTER TABLE public.asistencia_multiple
            RENAME COLUMN id_asistencia_multiple TO id;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'id'
    ) THEN
        ALTER TABLE public.asistencia_multiple
            ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_index i
        INNER JOIN pg_class c ON c.oid = i.indrelid
        INNER JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname = 'asistencia_multiple'
          AND i.indisprimary
    ) THEN
        ALTER TABLE public.asistencia_multiple
            ADD CONSTRAINT asistencia_multiple_pkey PRIMARY KEY (id);
    END IF;
END $$;

ALTER TABLE public.asistencia_multiple
    ADD COLUMN IF NOT EXISTS id_trabajador TEXT,
    ADD COLUMN IF NOT EXISTS id_tienda TEXT,
    ADD COLUMN IF NOT EXISTS hora_marca TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS ubicacion JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS tipo TEXT NOT NULL DEFAULT 'MULTIPLE';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'ubicacion'
          AND udt_name <> 'jsonb'
    ) THEN
        ALTER TABLE public.asistencia_multiple
            ALTER COLUMN ubicacion DROP DEFAULT;
        ALTER TABLE public.asistencia_multiple
            ALTER COLUMN ubicacion TYPE JSONB
            USING CASE
                WHEN ubicacion IS NULL OR trim(ubicacion::TEXT) = '' THEN '{}'::JSONB
                ELSE ubicacion::JSONB
            END;
    END IF;
END $$;

UPDATE public.asistencia_multiple
SET ubicacion = '{}'::JSONB
WHERE ubicacion IS NULL;

UPDATE public.asistencia_multiple
SET tipo = CASE
    WHEN upper(trim(COALESCE(tipo, ''))) = 'NORMAL' THEN 'NORMAL'
    ELSE 'MULTIPLE'
END;

ALTER TABLE public.asistencia_multiple
    ALTER COLUMN id_trabajador TYPE TEXT USING id_trabajador::TEXT,
    ALTER COLUMN id_tienda TYPE TEXT USING id_tienda::TEXT,
    ALTER COLUMN hora_marca TYPE TIMESTAMPTZ USING hora_marca::TIMESTAMPTZ,
    ALTER COLUMN ubicacion SET DEFAULT '{}'::JSONB,
    ALTER COLUMN ubicacion SET NOT NULL,
    ALTER COLUMN tipo TYPE TEXT USING tipo::TEXT,
    ALTER COLUMN tipo SET DEFAULT 'MULTIPLE',
    ALTER COLUMN tipo SET NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'ubicaciones'
    ) THEN
        UPDATE public.asistencia_multiple
        SET
            id_trabajador = COALESCE(
                NULLIF(ubicaciones ->> 'dni_trabajador', ''),
                NULLIF(id_trabajador, ''),
                NULLIF(ubicaciones ->> 'id_trabajador', '')
            ),
            id_tienda = COALESCE(
                NULLIF(ubicaciones ->> 'id_tienda_qr', ''),
                NULLIF(id_tienda, ''),
                NULLIF(ubicaciones ->> 'id_tienda_asignada', '')
            ),
            ubicacion = CASE
                WHEN ubicacion IS NULL OR ubicacion = '{}'::JSONB THEN jsonb_strip_nulls(jsonb_build_object(
                    'latitud', ubicaciones -> 'latitud',
                    'longitud', ubicaciones -> 'longitud'
                ))
                ELSE ubicacion
            END,
            tipo = CASE
                WHEN upper(COALESCE(ubicaciones ->> 'tipo', '')) = 'NORMAL'
                  OR lower(COALESCE(ubicaciones ->> 'origen', '')) = 'normal'
                THEN 'NORMAL'
                ELSE 'MULTIPLE'
            END
        WHERE ubicaciones IS NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'asistencia_multiple'
          AND column_name = 'Fecha'
    ) THEN
        UPDATE public.asistencia_multiple
        SET hora_marca = COALESCE(hora_marca, "Fecha"::TIMESTAMPTZ)
        WHERE hora_marca IS NULL
          AND "Fecha" IS NOT NULL;
    END IF;
END $$;

UPDATE public.asistencia_multiple
SET
    tipo = CASE
        WHEN upper(trim(COALESCE(tipo, ''))) = 'NORMAL'
          OR lower(COALESCE(ubicacion ->> 'origen', '')) = 'normal'
        THEN 'NORMAL'
        ELSE 'MULTIPLE'
    END,
    ubicacion = jsonb_strip_nulls(jsonb_build_object(
        'latitud', ubicacion -> 'latitud',
        'longitud', ubicacion -> 'longitud'
    ));

ALTER TABLE public.asistencia_multiple
    DROP CONSTRAINT IF EXISTS asistencia_multiple_tipo_check;

ALTER TABLE public.asistencia_multiple
    ADD CONSTRAINT asistencia_multiple_tipo_check
    CHECK (tipo IN ('NORMAL', 'MULTIPLE'));

ALTER TABLE public.asistencia_multiple
    DROP COLUMN IF EXISTS id_asistencia_multiple,
    DROP COLUMN IF EXISTS id_trabajador_nombre,
    DROP COLUMN IF EXISTS id_trabajador_cargo,
    DROP COLUMN IF EXISTS id_tienda_nombre,
    DROP COLUMN IF EXISTS id_tienda_direccion,
    DROP COLUMN IF EXISTS ubicaciones,
    DROP COLUMN IF EXISTS "Fecha",
    DROP COLUMN IF EXISTS created_at;

NOTIFY pgrst, 'reload schema';
