// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPrpez1NdkuX6ytetIJUwtwdrRYcyjxbY',
    appId: '1:647657035938:ios:716e0c673bb1e6a5d99ffb',
    messagingSenderId: '647657035938',
    projectId: 'almacen-remates',
    storageBucket: 'almacen-remates.firebasestorage.app',
    iosBundleId: 'com.example.trabajadorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaIeENaM8iz0XRM-hODNtb_gSpxkpb3Iw',
    appId: '1:647657035938:web:c22350721e3482bad99ffb',
    messagingSenderId: '647657035938',
    projectId: 'almacen-remates',
    authDomain: 'almacen-remates.firebaseapp.com',
    storageBucket: 'almacen-remates.firebasestorage.app',
    measurementId: 'G-KTBWB5BP8B',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaIeENaM8iz0XRM-hODNtb_gSpxkpb3Iw',
    appId: '1:647657035938:web:c22350721e3482bad99ffb',
    messagingSenderId: '647657035938',
    projectId: 'almacen-remates',
    authDomain: 'almacen-remates.firebaseapp.com',
    storageBucket: 'almacen-remates.firebasestorage.app',
    measurementId: 'G-KTBWB5BP8B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPrpez1NdkuX6ytetIJUwtwdrRYcyjxbY',
    appId: '1:647657035938:ios:716e0c673bb1e6a5d99ffb',
    messagingSenderId: '647657035938',
    projectId: 'almacen-remates',
    storageBucket: 'almacen-remates.firebasestorage.app',
    iosBundleId: 'com.example.trabajadorApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCayjauoc4v5JtFY9So5igTZhlyy0TBmzw',
    appId: '1:647657035938:android:185c29875fa7e6afd99ffb',
    messagingSenderId: '647657035938',
    projectId: 'almacen-remates',
    storageBucket: 'almacen-remates.firebasestorage.app',
  );

}